---
- hosts: all
  sudo: yes
  tasks:
    - name: start ntpd
      service: name=ntpd state=started

    - name: update repositories
      yum: name=* state=latest

    - name: update ansible
      yum: name=ansible state=latest

    - name: clone xsce-playbooks repository
      git: repo=git@sugardextrose.org:xsce-playbooks
           dest=/home/vagrant/xsce-playbooks
