---
- hosts: all
  sudo: yes
  tasks:
    - name: disable selinux
      selinux: state=disabled

    - name: install vim
      yum: name=vim state=present

    - name: update git
      yum: name=git state=latest

    - name: update ansible
      yum: name=ansible state=latest

    - name: use ansible form source code
      git: repo=https://github.com/ansible/ansible.git
           dest=/home/vagrant/ansible

    - name: install form ansible source
      command: python setup.py install chdir=/home/vagrant/ansible

- hosts: all
  user: vagrant
  tasks:
    - name: clone dxs repository
      git: repo=https://github.com/activitycentral/dxs.git
           dest=/home/vagrant/dxs
